### ISSUE TITLE
Jenkins runs Flutter test forever

### ISSUE THREAD

**Issue by jasonwun** [sudhanshu-15/jenkinsflutter#1]
I found your article and want to implement that in my company as well. However, the Jenkins run task on Flutter test it takes forever. Have you met the same problem as well?

**Comment by sudhanshu-15** [comment]
Hi, I did not face any such issue in the past. You can me be try to check which version of Flutter is being installed in the docker instance. I suspect it might be related Flutter version. Did you make any specific change to the jenkins file Are you running flutter test with coverage?

**Comment by jasonwun** [comment]
Hello,

I found that it is actually related to network issue on first time usage of Flutter and it takes some time to download or install something from Google server. Once this "installation" is completed, the following build will be fast instead.
